title:               Lucas Zhang
url:                 https://lucaszz-econ.github.io
baseurl:             ""

avatar: "/favicon.png"

markdown:            kramdown
highlighter:         rouge

exclude:             ['*.sublime-*', 'README.md', 'LICENSE', 'Gemfile', 'Gemfile.lock', 'vendor/bundle']

permalink:           pretty
paginate:            5
paginate_path:       /blog/:num

sass:
  sass_dir:          _sass
  style:             :compressed

author:
  name:              Lucas Zhang
  url:               lucaszz-econ.github.io
  email:             lucaszz@ucla.edu

plugins:
  - jekyll-coffeescript
  - jekyll-paginate
  - jekyll-gist
